# Generated by Django 4.2 on 2023-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_rename_uid_students_password_students_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=50, null=True)),
                ('teachers_id', models.CharField(default=None, max_length=50, null=True)),
                ('fullname', models.CharField(default=None, max_length=50, null=True)),
                ('password', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
