# Generated by Django 4.2 on 2023-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='cgpa1',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa2',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa3',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa4',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa5',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa6',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa7',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cgpa8',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
